// Generated by CoffeeScript 1.9.2
(function() {
  var snippet,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  window.check_code = function(string, arg) {
    var i, len, must_has, must_hasnt, must_have, mustnt_has, mustnt_have, node, parsed, ref, structure_has, structures, type, visit_node;
    must_have = arg.must_have, mustnt_have = arg.mustnt_have, structures = arg.structures;
    must_have || (must_have = []);
    mustnt_have || (mustnt_have = []);
    structures || (structures = []);
    parsed = esprima.parse(string);
    console.log(parsed);
    must_has = [];
    mustnt_has = [];
    structure_has = $.extend(true, [], structures);
    visit_node = function(node, structure_pointers) {
      var ref, ref1, ref2, ref3, visit_child;
      if (node === null) {
        return;
      }
      if ((ref = node.type, indexOf.call(mustnt_have, ref) >= 0) && (ref1 = node.type, indexOf.call(mustnt_has, ref1) < 0)) {
        mustnt_has.push(node.type);
      }
      if ((ref2 = node.type, indexOf.call(must_have, ref2) >= 0) && (ref3 = node.type, indexOf.call(must_has, ref3) < 0)) {
        console.log("has", node.type);
        must_has.push(node.type);
      }
      visit_child = function(node, key, found_structures) {
        var child, child_node, child_structure_pointers, i, len;
        child_structure_pointers = [];
        child = node[key];
        if ($.isArray(child)) {
          for (i = 0, len = child.length; i < len; i++) {
            child_node = child[i];
            visit_node(child_node, child_structure_pointers);
          }
        } else if (child) {
          visit_node(child, child_structure_pointers);
        }
        return void 0;
      };
      if (node.type === 'IfStatement') {
        visit_child(node, 'consequent');
        visit_child(node, 'alternate');
      }
      if (node.body != null) {
        visit_child(node, 'body');
      }
      return void 0;
    };
    ref = parsed.body;
    for (i = 0, len = ref.length; i < len; i++) {
      node = ref[i];
      visit_node(node, [structure_has]);
    }
    must_hasnt = (function() {
      var j, len1, results;
      results = [];
      for (j = 0, len1 = must_have.length; j < len1; j++) {
        type = must_have[j];
        if (indexOf.call(must_has, type) < 0) {
          results.push(type);
        }
      }
      return results;
    })();
    return {
      must_hasnt: must_hasnt,
      mustnt_has: mustnt_has
    };
  };

  snippet = "var y = 5;\nif(y){\n	for(x=0; x<5; x++){\n		console.log('yay')\n	}\n}";

}).call(this);
